# Generated by Django 5.2.4 on 2025-10-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
